### ISSUE TITLE
How to set fireplacemode with cli?

### ISSUE THREAD

**Issue by waltervl** [robertklep/nefit-easy-cli#3]
I try to swith on/off the fireplace mode from a terminal session.
When I use "easy get /ecus/rrc/userprogram/fireplacefunction" I get the following correct response:
{"id":"/ecus/rrc/userprogram/fireplacefunction","type":"stringValue","recordable":0,"writeable":1,"value":"on"}

But when I want to switch off with "easy put" I do not seem to get a proper syntax.
I tried many syntaxes like:
easy put /ecus/rrc/userprogram/fireplacefunction {"value":"off"}
easy put /ecus/rrc/userprogram/fireplacefunction off
easy put /ecus/rrc/userprogram/fireplacefunction "value":"off"

But all result in an error see below. What am I doing wrong?
{ Error: INVALID_RESPONSE
    at send.then.response (/usr/lib/node_modules/nefit-easy-cli/node_modules/nefit-easy-core/lib/index.js:247:23)
    at tryCatcher (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/util.js:16:23)
...........
response:
   { protocolVersion: 'HTTP/1.0',
     statusCode: '400',
     statusMessage: 'Bad Request',
     headers: { 'Content-Type': 'application/json', connection: 'close' },
     body: '' } }

**Comment by robertklep** [comment]
Try this:
```
easy put /ecus/rrc/userprogram/fireplacefunction '{"value":"off"}'
```

**Comment by waltervl** [comment]
Thanks! Did not try that one.... It worked!
