### ISSUE TITLE
SyntaxError: Unexpected token H in JSON at position 0

### ISSUE THREAD

**Issue by Sonusss** [robertklep/nefit-easy-cli#4]
Hi,

This command line utility fits better my needs but I have also issues.
I tried with and without single quoting credential 

Command: easy --serial=*** --access-key=*** --password=*** -V status

> SyntaxError: Unexpected token H in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at pending.(anonymous function).send.then.response (/usr/lib/node_modules/nefit-easy-cli/node_modules/nefit-easy-core/lib/index.js:216:30)
>     at tryCatcher (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:547:31)
>     at Promise._settlePromise (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:604:18)
>     at Promise._settlePromise0 (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:649:10)
>     at Promise._settlePromises (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:729:18)
>     at _drainQueueStep (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:93:12)
>     at _drainQueue (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:86:9)
>     at Async._drainQueues (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:15:14)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)
> SyntaxError: Unexpected token H in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at pending.(anonymous function).send.then.response (/usr/lib/node_modules/nefit-easy-cli/node_modules/nefit-easy-core/lib/index.js:216:30)
>     at tryCatcher (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:547:31)
>     at Promise._settlePromise (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:604:18)
>     at Promise._settlePromise0 (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:649:10)
>     at Promise._settlePromises (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:729:18)
>     at _drainQueueStep (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:93:12)
>     at _drainQueue (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:86:9)
>     at Async._drainQueues (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:15:14)
>     at runCallback (timers.js:705:18)
>     at tryOnImmediate (timers.js:676:5)
>     at processImmediate (timers.js:658:5)

**Comment by robertklep** [comment]
See my response here: https://github.com/robertklep/bosch-xmpp/issues/7#issuecomment-604424699

**Comment by Sonusss** [comment]
Indeed I changed the password removing special characters and it works !
