### ISSUE TITLE
unable to whrith codes

### ISSUE THREAD

**Issue by TGMivo** [robertklep/nefit-easy-cli#5]
pi@raspberrypi:~ $ sudo easy-server --serial=MYSERIAL
Error: missing password
pi@raspberrypi:~ $ sudo easy-server --password=MYPASSW
Error: missing access key
pi@raspberrypi:~ $ sudo easy-server --access-key=MYACCESkey
Error: missing password

Whats wrong?

**Comment by robertklep** [comment]
You need to pass all arguments at once:
```
$ sudo easy-server --serial=MYSERIAL --password=MYPASSW --access-key=MYACCESkey
```

**Comment by TGMivo** [comment]
I deleted grafana, (changing grafana port didn't work)
The server it worked for 30 minutes and stoped

pi@raspberrypi:~ $ sudo easy-server --serial=9999999 --password=88888 --access-key=77777777
Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1317:16)
    at listenInCluster (net.js:1365:12)
    at doListen (net.js:1502:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000
}

There is something else on port 3000

pi@raspberrypi:~ $ sudo netstat -plunt |grep :3000
tcp6       0      0 :::3000                 :::*                    LISTEN      19987/grafana-server
pi@raspberrypi:~ $ sudo kill -9 19987
pi@raspberrypi:~ $ sudo netstat -plunt |grep :3000
tcp        0      0 127.0.0.1:3000          0.0.0.0:*               LISTEN      23690/node


Killing 19987 worked, i recieve nog data in Domoticz. But grafana is deleted how can i stop grafana for a restart?
